name: 𝚳𝐒𝚵𝐋𝚫-𝐂𝚮𝐔𝚰-𝚾𝚳𝐃
services:
  - name: 𝚳𝐒𝚵𝐋𝚫-𝐂𝚮𝐔𝚰-𝚾𝚳𝐃-service
    type: web
    ports:
      - 5000
    routes:
      - path: "/"
    build:
      type: docker
      dockerfile: ./Dockerfile
    regions:
      - fra
      - sin
      
