name: 𝐊𝐀𝐋𝐈-𝐌𝐃𝟏
services:
  - name: 𝐊𝐀𝐋𝐈-𝐌𝐃𝟏-service
    type: web
    ports:
      - 5000
    routes:
      - path: "/"
    build:
      type: docker
      dockerfile: ./Dockerfile
    regions:
      - fra
      - sin
      
